name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  APP_NAME: storageserver

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'src/go.mod'
      
      - name: Run tests
        run: make test
