name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  APP_NAME: storageserver

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
      
      - name: Run tests
        run: go test  -v ./...
